# Generated by Django 3.0 on 2020-04-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200418_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(verbose_name='dd/mm/yyyy'),
        ),
    ]
