# Generated by Django 3.0 on 2020-04-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200420_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='category',
            new_name='category_type',
        ),
    ]
