# Generated by Django 3.0 on 2020-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20200423_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
