# Generated by Django 3.0 on 2020-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
