# Generated by Django 3.0 on 2020-05-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20200504_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.CharField(default='abc', max_length=120),
            preserve_default=False,
        ),
    ]
